#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &

picom --experimental-backends &

feh --bg-fill ~/Pictures/wallpapers-master/0053.jpg --bg-fill ~/Pictures/wallpapers-master/0298.jpg

$HOME/.config/polybar/launch.sh

# nm-applet &

# blueberry-tray &

bspc monitor eDP -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 25

bspc config normal_border_color "#44475a"
bspc config active_border_color "bd93f9"
bspc config focused_border_color "ff79c6"
bspc config presel_feedback_color "6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
