#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill ~/Pictures/wallpapers-master/0305.jpg -bg-fill ~/Pictures/wallpapers-master/0240.jpg
# feh --bg-fill /usr/share/backgrounds/bspwm/wall.png -bg-fill ~/Pictures/wallpapers-master/0012.jpg
picom &
picom --experimental-backends &
# /usr/bin/emacs --daemon &

bspc monitor eDP-1  -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 35

# DT's colors
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Discord desktop='^9' state=tiled follow=on
#bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zathura state=tiled

